### ISSUE TITLE
Make layout work on phone-sized screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/quake#10]
As of this writing, the layout of the app is locked to portrait mode and looks pretty decent on my primary test device, which is a Samsung Tab S7 tablet.  I just worked with @jessegreenberg to test it on his Samsung Galaxy S8 phone, and the layout doesn't look very good at all.  Below are some images captured from that testing, which was done over Zoom.  I'll need to figure out how to make this work better on the smaller screen.

![image](https://user-images.githubusercontent.com/3082831/160700040-9fe988e3-9ef6-4589-bd8a-21da6d468d5d.png)

**Comment by jbphet** [comment]
@jessegreenberg and I tested this on his phone today, and he reported that the layout is much improved.  The UI controls fit on the first two screens ("Clicks" and "Buzzes"), and they work on the third screen ("Patterns") but require a bit of scrolling.  The scrolling didn't impress him as problematic.

I'd like to get a bit more feedback from other users before closing this, but I think I'll wait until after I have a version that is available via the Google Play store, which should be soon.

**Comment by jbphet** [comment]
The layout is working quite well on phone-sized screens at this point, and v0.0.1 is published for internal testing, and is successfully running on the phones of several team members.  I'm sure further work will be required in this area, but the primary problem is resolved.  Closing.

**Comment by stemilymill** [comment]
I can make this a separate issue if you'd like, but since it is phone layout related I'm putting it here. 

https://github.com/phetsims/qa/issues/842

**NOTE:** My phone has a weird screen ratio, so things like this are fairly common.

Test device: Samsung Galaxy s21 Ultra, android version 12

There is some odd scrolling behavior where there shouldn't be scrolling. Usability is only very slightly impacted in the first example, and not at all in the second.

https://user-images.githubusercontent.com/85511101/195393458-664f99cf-2aee-4544-a953-2d2d1b8bed19.mp4

https://user-images.githubusercontent.com/85511101/195393398-17e5ad5d-c2d2-4975-910d-820f726ca51e.mp4
